name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.24
        env:
          MYSQL_ROOT_PASSWORD: "root_password"
          MYSQL_DATABASE: "message_bus_test"
          MYSQL_USER: "username"
          MYSQL_PASSWORD: "password"
          MYSQL_ROOT_HOST: "0.0.0.0"
        ports:
          - "3306:3306"

    strategy:
      fail-fast: true
      matrix:
        php: [8.1]
        stability: [prefer-lowest, prefer-stable]

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          coverage: none

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Setup database
        run: php tests/wait-for-and-setup-database.php

      - name: Execute tests
        run: vendor/bin/phpunit
